file_format: "1"
id: totem
name: TOTEM
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeeduino_xiao_ble]
features:
  - keys
  - display
  - studio
siblings:
  - totme_dongle
  - totem_left
  - totem_right
