file_format: "1"
id: totem
name: TOTEM
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeeduino_xiao_ble, nice_nano_v2]
features:
  - keys
  - display
  - studio
outputs:
  - ble
siblings:
  - totme_dongle
  - totem_left
  - totem_right
